try:
    x = 1/0
    print(x)
except:
    print("An exception occurred!")